### ISSUE TITLE
Spam Click Button

### ISSUE THREAD

**Issue by tejmen** [tejmen/Milk.io#7]
### A button that disables the cow animation so spam clicking can be achieved

**Comment by appcreatorguy** [comment]
Im guessing this is a follow up for #4

**Comment by tejmen** [comment]
yes

**Comment by tejmen** [comment]
Fixed in referenced commit [https://github.com/tejmen/Milk.io/commit/9f6ef7c3e975bb0a83a4f5c5d7fd4fe1ea815185](url)
